local M = {}
local languages = {}
local function declare_lang(babelname, lang)
  languages[lang] = babelname
end

declare_lang("UKenglish","en-GB")
declare_lang("USenglish","en-US")
declare_lang("acadian","fr")
declare_lang("albanian","sq")
declare_lang("american","en-US")
declare_lang("amharic","am")
declare_lang("arabic","ar")
declare_lang("armenian","hy")
declare_lang("australian","en-US")
declare_lang("austrian","de")
declare_lang("basque","eu")
declare_lang("bengali","bn")
declare_lang("brazilian","pt")
declare_lang("brazil","pt")
declare_lang("breton","br")
declare_lang("british","en-GB")
declare_lang("bulgarian","bg")
declare_lang("canadian","en-US")
declare_lang("canadien","fr")
declare_lang("catalan","ca")
declare_lang("croatian","hr")
declare_lang("czech","cs")
declare_lang("danish","da")
declare_lang("divehi","dv")
declare_lang("dutch","nl")
declare_lang("english","en")
declare_lang("esperanto","eo")
declare_lang("estonian","et")
declare_lang("finnish","fi")
declare_lang("francais","fr")
declare_lang("french","fr")
declare_lang("galician","gl")
declare_lang("germanb","de")
declare_lang("german","de")
declare_lang("greek","el")
declare_lang("hebrew","he")
declare_lang("hindi","hi")
declare_lang("hungarian","hu")
declare_lang("icelandic","is")
declare_lang("interlingua","ia")
declare_lang("irish","ga")
declare_lang("italian","it")
declare_lang("kannada","kn")
declare_lang("khmer","km")
declare_lang("korean","ko")
declare_lang("lao","lo")
declare_lang("latin","la")
declare_lang("latvian","lv")
declare_lang("lithuanian","lt")
declare_lang("lowersorbian","dsb")
declare_lang("magyar","hu")
declare_lang("malayalam","ml")
declare_lang("marathi","mr")
declare_lang("naustrian","de")
declare_lang("english","en")
declare_lang("ngerman","de")
declare_lang("norsk","no")
declare_lang("norwegiannynorsk","nn")
declare_lang("nynorsk","no")
declare_lang("occitan","oc")
declare_lang("oldchurchslavonic","cu")
declare_lang("persian","fa")
declare_lang("polish","pl")
declare_lang("polutonikogreek","el")
declare_lang("portuges","pt")
declare_lang("portuguese","pt")
declare_lang("romanian","ro")
declare_lang("romansh","rm")
declare_lang("russian","ru")
declare_lang("samin","se")
declare_lang("sanskrit","sa")
declare_lang("scottish","gd")
declare_lang("serbian","sr")
declare_lang("serbo-croatian","sh")
declare_lang("slovak","sk")
declare_lang("slovene","sl")
declare_lang("slovenian","sl")
declare_lang("spanish","es")
declare_lang("swedish","sv")
declare_lang("tamil","ta")
declare_lang("telugu","te")
declare_lang("thai","th")
declare_lang("tibetan","bo")
declare_lang("turkish","tr")
declare_lang("turkmen","tk")
declare_lang("ukrainian","uk")
declare_lang("uppersorbian","hsb")
declare_lang("urdu","ur")
declare_lang("vietnamese","vi")
declare_lang("welsh","cy")

function M.get_babel_name(lang)
  -- try to convert language shortcut used in HTML to a Babel name used in LaTeX
  local lang = lang or "en" -- use English if we cannot detect the document language
  return languages[lang] or languages[lang:match("^(.-)%-")]
end

return M
