name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Run make4ht
      # uses: michal-h21/make4ht-action@master
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          cd doc
          make4ht -j index -la debug -d out texblend-doc.tex
          cd ..
          mkdir out
          cp doc/out/*.* out
    - name: Publish the web pages
      uses:  peaceiris/actions-gh-pages@v3
      with:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PUBLISH_BRANCH: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
